language: php
php:
  - '5.6'
  - '7.0'
#cache:
#    directories:
#      - vendor
#      - $HOME/.composer/cache

install:
    - composer self-update
    - composer install
script:
    - php bin/codecept run
