language: php
php:
  - '5.6'
  - '7.0'
cache:
    directories:
      - vendor
      - $HOME/.composer/cache

before_script:
    - "composer install"
script:
    - "php ./vendor/bin/codecept run unit"
